package frontend;

import backend.*;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author reineckeKarin
 */
public class MitgliedHinzufuegenView extends javax.swing.JFrame {
    private final Mitgliederverwaltung verwaltung;
    DefaultListModel<String> abonnementModel;

    public MitgliedHinzufuegenView(Mitgliederverwaltung verwaltung) {
        initComponents();
        this.setSize(700,550);
        this.setResizable(false);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.verwaltung = verwaltung;

        abonnementModel = new DefaultListModel<>();
        for(Abonnement abos: Abonnement.values()){
            abonnementModel.addElement(abos.toString());
        }

        abonnementsList.setModel(abonnementModel);
        abonnementsList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        fitnessclubLabel = new javax.swing.JLabel();
        mitgliedLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        mitgliedsnummerTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        geburtsdatumTextField = new javax.swing.JTextField();
        mitgliedsnummerLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        geburtsdatumLabel = new javax.swing.JLabel();
        alterComboBox = new javax.swing.JComboBox<>();
        alterLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        statusLabel = new javax.swing.JLabel();
        abonnementsScrollPane = new javax.swing.JScrollPane();
        abonnementsList = new javax.swing.JList<>();
        abonnementsLabel = new javax.swing.JLabel();

        fitnessclubLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        fitnessclubLabel.setText("Delta Fitnessclub e.V.");
        fitnessclubLabel.setToolTipText("");
        fitnessclubLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mitgliedLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mitgliedLabel.setText("Mitglied");

        closeButton.setText("Abbrechen");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        addButton.setText("Speichern");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        geburtsdatumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geburtsdatumTextFieldActionPerformed(evt);
            }
        });

        mitgliedsnummerLabel.setText("Mitgliedsnummer");

        nameLabel.setText("Name");

        geburtsdatumLabel.setText("Geburtsdatum");

        alterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jung", "Erwachsen", "Senior" }));

        alterLabel.setText("Altersklasse");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktiv", "Passiv", "Ehemalig", "Ehrenmitglied" }));

        statusLabel.setText("Mitgliedsstatus");

        abonnementsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "abonnementModel" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        abonnementsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        abonnementsScrollPane.setViewportView(abonnementsList);

        abonnementsLabel.setText("Abonnements");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(31, 31, 31)
                                                                .addComponent(fitnessclubLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(alterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(alterLabel))))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(closeButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(addButton))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(mitgliedsnummerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(mitgliedsnummerTextField))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(80, 80, 80)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(mitgliedLabel)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(13, 13, 13)
                                                                                                .addComponent(nameLabel)
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                .addComponent(geburtsdatumLabel))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(55, 55, 55)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(statusLabel)
                                                                                                .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(abonnementsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(abonnementsLabel)
                                                                                                .addComponent(geburtsdatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fitnessclubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mitgliedLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mitgliedsnummerLabel)
                                        .addComponent(nameLabel)
                                        .addComponent(geburtsdatumLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mitgliedsnummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(geburtsdatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(alterLabel)
                                        .addComponent(statusLabel)
                                        .addComponent(abonnementsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(alterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(195, 195, 195)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(closeButton)
                                                        .addComponent(addButton)))
                                        .addComponent(abonnementsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
    }// </editor-fold>

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MitgliederverwaltungView mitgliederverwaltungFenster = new MitgliederverwaltungView();
        mitgliederverwaltungFenster.setVisible(true);
        dispose();
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {
        var status = this.statusComboBox.getSelectedIndex();
        Mitgliedsstatus mitgliedsstatus = Mitgliedsstatus.PASSIV;
        switch (status){
            case 0:
                mitgliedsstatus = Mitgliedsstatus.AKTIV;
                break;
            case 1:
                mitgliedsstatus = Mitgliedsstatus.PASSIV;
                break;
            case 2:
                mitgliedsstatus = Mitgliedsstatus.EHEMALIG;
                break;
            case 3:
                mitgliedsstatus = Mitgliedsstatus.EHRENMITGLIED;
                break;
        }

        var alter = this.alterComboBox.getSelectedIndex();
        Altersklasse altersklasse = Altersklasse.ERWACHSEN;
        switch (alter){
            case 0:
                altersklasse = Altersklasse.JUNG;
                break;
            case 1:
                altersklasse = Altersklasse.ERWACHSEN;
                break;
            case 2:
                altersklasse = Altersklasse.SENIOR;
                break;
        }

        List<String> abos =  abonnementsList.getSelectedValuesList();
        List<Abonnement> abonnements = new ArrayList<>();
        for (String abo : abos){
            switch(abo){
                case "SAUNA":
                    abonnements.add(Abonnement.SAUNA);
                    break;
                case "PARKPLATZ":
                    abonnements.add(Abonnement.PARKPLATZ);
                    break;
                case "DUSCHE":
                    abonnements.add(Abonnement.DUSCHE);
                    break;
                case "BODYPUMP":
                    abonnements.add(Abonnement.BODYPUMP);
                    break;
                case "INDOOR_CYCLING":
                    abonnements.add(Abonnement.INDOOR_CYCLING);
                    break;
                case "BODABALANCE":
                    abonnements.add(Abonnement.BODABALANCE);
                    break;
                case "LES_MILLS_GRIT":
                    abonnements.add(Abonnement.LES_MILLS_GRIT);
                    break;
                case "BODYSTYLING":
                    abonnements.add(Abonnement.BODYSTYLING);
                    break;
                case "RUECKEN_SOFT":
                    abonnements.add(Abonnement.RUECKEN_SOFT);
                    break;
                case "RUECKEN_AKTIV":
                    abonnements.add(Abonnement.RUECKEN_AKTIV);
                    break;
                case "BAUCH_BEINE_PO":
                    abonnements.add(Abonnement.BAUCH_BEINE_PO);
                    break;
                case "CARDIO_MEETS_WELLNESS":
                    abonnements.add(Abonnement.CARDIO_MEETS_WELLNESS);
                    break;
            }
        }

        verwaltung.fuegeMitgliedHinzu(mitgliedsstatus, altersklasse, null, abonnements,
                new ArrayList<Rechnung>(), nameTextField.getText(), geburtsdatumTextField.getText());

        MitgliederverwaltungView mitgliederverwaltungFenster = new MitgliederverwaltungView();
        mitgliederverwaltungFenster.setVisible(true);
        dispose();
    }

    private void geburtsdatumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }


    // Variables declaration - do not modify
    private javax.swing.JLabel abonnementsLabel;
    private javax.swing.JList<String> abonnementsList;
    private javax.swing.JScrollPane abonnementsScrollPane;
    private javax.swing.JButton addButton;
    private javax.swing.JComboBox<String> alterComboBox;
    private javax.swing.JLabel alterLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fitnessclubLabel;
    private javax.swing.JLabel geburtsdatumLabel;
    private javax.swing.JTextField geburtsdatumTextField;
    private javax.swing.JLabel mitgliedLabel;
    private javax.swing.JLabel mitgliedsnummerLabel;
    private javax.swing.JTextField mitgliedsnummerTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration
}
